### ISSUE TITLE
Regularization, Feature Importance for back-to-back regression

### ISSUE THREAD

**Issue by ssaket** [unfoldtoolbox/Unfold.jl#74]
I think it would be useful to have an option of adding regularization to the current back-to-back regression solver. Additionally, if following could be implemented -

- B2B feature importance
- Forward feature importance

**Comment by behinger** [comment]
have a look at #42 for regularization/CV  - I can make b2b much faster, but I haven't found the time yet...

**Comment by ssaket** [comment]
@behinger I see some new package (dependencies) required for #42 Do we want them? I was thinking of a native solution from scratch.

**Comment by behinger** [comment]
I'm mostly trying out things. I dislike writing native solutions from scratch because I typically don't have the time to test them through & typically I can't optimize them as much.

But clearly, there are too many dependencies, i.e. one library to do the job should be enough ;-) For me B2B is still very much in research-domain, e.g. I applied it to P300 RT data but it "didnt work", i.e. didnt take RT into account even though univariatly it does

**Comment by behinger** [comment]
btw. very welcome to modify my PR

I think you asked for the P3 data somewhere, sorry I forgot.

This is a modified version of your DataAnalysis.jl notebook from the FaPra
https://gist.github.com/f96075ad4ce8632681c87357bd1d3c1a

The p3 data you can find here (careful 700mb): https://cloud.wirdreibei.de/s/i3r2xT9Ep9SC9P9

I didn't double check it,  running a bit out of time to do everything I want. If you have trouble just mention it here
